[package]
name = "breakout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.45.0"
gl = "0.14.0"
image = "0.24.2"
cgmath = "0.18.0"
lazy_static = "1.2.0"
rand = "0.8.5"
cpal = "0.13.5"